package com.datu.patient;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CollectionResponse implements java.io.Serializable {
  static final long serialVersionUID = 1L;

  @org.kie.api.definition.type.Label("collectionResponseId")
  private int collectionResponseId;
  @org.kie.api.definition.type.Label("collectionId")
  private int collectionId;

  @org.kie.api.definition.type.Description(value = "List of TileIDs that have been responded within collection")
  @org.kie.api.definition.type.Label(value = "collectionItems")
  private List<CollectionItem> collectionItems = new ArrayList<CollectionItem>();

  @org.kie.api.definition.type.Label(value = "dismissFlag")
  private String dismissFlag;

  @org.kie.api.definition.type.Label(value = "responseDateTime")
  private Date responseDateTime;

  public CollectionResponse() {
  }

  public int getCollectionId() {
    return this.collectionId;
  }

  public void setCollectionId(int collectionId) {
    this.collectionId = collectionId;
  }

  public int getCollectionResponseId() {
    return this.collectionResponseId;
  }

  public void setCollectionResponseId(int collectionResponseId) {
    this.collectionResponseId = collectionResponseId;
  }

  public java.util.List<CollectionItem> getCollectionItems() {
    return this.collectionItems;
  }

  public void setCollectionItems(java.util.List<CollectionItem> collectionItems) {
    this.collectionItems = collectionItems;
  }

  public java.lang.String getDismissFlag() {
    return this.dismissFlag;
  }

  public void setDismissFlag(java.lang.String dismissFlag) {
    this.dismissFlag = dismissFlag;
  }

  public java.util.Date getResponseDateTime() {
    return this.responseDateTime;
  }

  public void setResponseDateTime(java.util.Date responseDateTime) {
    this.responseDateTime = responseDateTime;
  }

  public CollectionResponse(int collectionResponseId, int collectionId,
      java.util.List<CollectionItem> collectionItems, java.lang.String dismissFlag,
      java.util.Date responseDateTime) {
    this.collectionResponseId = collectionResponseId;
    this.collectionId = collectionId;
    this.collectionItems = collectionItems;
    this.dismissFlag = dismissFlag;
    this.responseDateTime = responseDateTime;
  }
}