package com.datu.patient;

import java.util.Date;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProgramEnrollment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "programId")
   private int programId;
   @org.kie.api.definition.type.Label(value = "enrollmentDate")
   private Date enrollmentDate;
   @org.kie.api.definition.type.Label(value = "enrollmentStartDate")
   private Date enrollmentStartDate;
   @org.kie.api.definition.type.Label(value = "enrollmentEndDate")
   private Date enrollmentEndDate;
   @org.kie.api.definition.type.Label(value = "status")
   private java.lang.String status;

   public ProgramEnrollment()
   {
   }

   public int getProgramId()
   {
      return this.programId;
   }

   public void setProgramId(int programId)
   {
      this.programId = programId;
   }

   public Date getEnrollmentDate()
   {
      return this.enrollmentDate;
   }

   public void setEnrollmentDate(Date enrollmentDate)
   {
      this.enrollmentDate = enrollmentDate;
   }

   public Date getEnrollmentStartDate()
   {
      return this.enrollmentStartDate;
   }

   public void setEnrollmentStartDate(Date enrollmentStartDate)
   {
      this.enrollmentStartDate = enrollmentStartDate;
   }

   public Date getEnrollmentEndDate()
   {
      return this.enrollmentEndDate;
   }

   public void setEnrollmentEndDate(Date enrollmentEndDate)
   {
      this.enrollmentEndDate = enrollmentEndDate;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public ProgramEnrollment(int programId, Date enrollmentDate,
         Date enrollmentStartDate,
         Date enrollmentEndDate, java.lang.String status)
   {
      this.programId = programId;
      this.enrollmentDate = enrollmentDate;
      this.enrollmentStartDate = enrollmentStartDate;
      this.enrollmentEndDate = enrollmentEndDate;
      this.status = status;
   }

}